name: Build desktop app

on:
  push:
    branches:
      - main
    paths:
      - packages/desktop/**

jobs:
  build:
    name: Build desktop app
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: corepack enable
      - run: pnpm i
      - run: pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
